// Add Policy

export const CHANGE_SINGLE_PREMIUM_VALUE = 'CHANGE_SINGLE_PREMIUM_VALUE';
export const CHANGE_PREMIUM_MODE_VALUE = 'CHANGE_PREMIUM_MODE_VALUE';
export const CHANGE_POLICY_DATE = 'CHANGE_POLICY_DATE';
export const SAVE_POLICY_FORM_START = 'SAVE_POLICY_FORM_START';
export const SAVE_POLICY_FORM_SUCCESS = 'SAVE_POLICY_FORM_SUCCESS';
export const SAVE_POLICY_FORM_FAILURE = 'SAVE_POLICY_FORM_FAILURE';

export const CREATE_CALCULATE_COMMISSION = 'CREATE_CALCULATE_COMMISSION';

// My Policy

export const MY_POLICY_LIST_START = 'MY_POLICY_LIST_START';
export const MY_POLICY_LIST_SUCCESS = 'MY_POLICY_LIST_SUCCESS';
export const MY_POLICY_LIST_FAILURE = 'MY_POLICY_LIST_FAILURE';

export const MY_POLICY_LIST_ITEM_CLICKED = 'MY_POLICY_LIST_ITEM_CLICKED';
