// Add Policy

export const CHANGE_SINGLE_PREMIUM_VALUE = 'CHANGE_SINGLE_PREMIUM_VALUE';
export const CHANGE_PREMIUM_MODE_VALUE = 'CHANGE_PREMIUM_MODE_VALUE';
export const CHANGE_POLICY_DATE = 'CHANGE_POLICY_DATE';
export const SAVE_POLICY_FORM_START = 'SAVE_POLICY_FORM_START';
export const SAVE_POLICY_FORM_SUCCESS = 'SAVE_POLICY_FORM_SUCCESS';
export const SAVE_POLICY_FORM_FAILURE = 'SAVE_POLICY_FORM_FAILURE';

export const CREATE_CALCULATE_COMMISSION = 'CREATE_CALCULATE_COMMISSION';
export const CHANGE_CONFIRMATION_MODAL_STATUS = 'CHANGE_CONFIRMATION_MODAL_STATUS';

// My Policy

export const MY_POLICY_LIST_START = 'MY_POLICY_LIST_START';
export const MY_POLICY_LIST_SUCCESS = 'MY_POLICY_LIST_SUCCESS';
export const MY_POLICY_LIST_FAILURE = 'MY_POLICY_LIST_FAILURE';

export const MY_POLICY_LIST_ITEM_CLICKED = 'MY_POLICY_LIST_ITEM_CLICKED';
export const DELETE_POLICY_ITEM_START = 'DELETE_POLICY_ITEM_START';
export const DELETE_POLICY_ITEM_SUCCESS = 'DELETE_POLICY_ITEM_SUCCESS';
export const DELETE_POLICY_ITEM_FAILURE = 'DELETE_POLICY_ITEM_FAILURE';


// My Commission

export const MY_COMMISSION_LIST_START = 'MY_COMMISSION_LIST_START';
export const MY_COMMISSION_LIST_SUCCESS = 'MY_COMMISSION_LIST_SUCCESS';
export const MY_COMMISSION_LIST_FAILURE = 'MY_COMMISSION_LIST_FAILURE';

export const MY_COMMISSION_LIST_ITEM_CLICKED = 'MY_COMMISSION_LIST_ITEM_CLICKED';
export const MY_COMMISSION_LIST_SEARCH_TEXT_CHANGED = 'MY_COMMISSION_LIST_SEARCH_TEXT_CHANGED';
